// Regenerates the resolution facades from the sibling deepseek-harness checkout.
// Harness imports resolve against its source or declarations; this external bundle's
// public subpaths resolve to their maintained implementation directories.
import { readFileSync, writeFileSync } from 'node:fs'

const HARNESS = new URL('../../deepseek-harness/', import.meta.url)
const raw = readFileSync(new URL('tsconfig.base.json', HARNESS), 'utf8')
const cleaned = raw
  .split('\n')
  .filter(line => !/^\s*\/\//.test(line))
  .join('\n')
  .replace(/^\s*\/\*[\s\S]*?\*\//gm, '')
const base = JSON.parse(cleaned)

const own = {
  '@wowyuarm/dsh-agent-team/host': ['./packages/agent-team/src/index.ts'],
  '@wowyuarm/dsh-agent-team/invariant': ['./packages/agent-team/src/invariant.ts'],
  '@wowyuarm/dsh-agent-team/types': ['./packages/agent-team/src/types.ts'],
  '@wowyuarm/dsh-agent-team/typert': ['./packages/agent-team/lib/typert.host.d.ts'],
  '@wowyuarm/dsh-agent-team/remote': ['./packages/agent-team/lib/typert.remote-client.js'],
  '@wowyuarm/dsh-agent-team/preset-roster': ['./packages/agent-team/src/preset-roster.ts'],
  '@wowyuarm/dsh-agent-team/member-context': ['./packages/agent-team/src/member-context.ts'],
  '@wowyuarm/dsh-agent-team/tools': ['./packages/tool-agent-team/src/index.ts'],
  '@wowyuarm/dsh-agent-team/client': ['./packages/client-agent-team/src/client/index.ts'],
}

const ownTypes = {
  ...own,
  '@wowyuarm/dsh-agent-team/remote': ['./packages/agent-team/lib/typert.remote-client.d.ts'],
}

const harnessSrc = {
  '@deepseek-ai/dsh-storage-sqlite': ['../deepseek-harness/packages/storage/storage-sqlite/src/index.ts'],
}
for (const [key, value] of Object.entries(base.compilerOptions.paths)) {
  harnessSrc[key] = (Array.isArray(value) ? value : [value])
    .map(path => path.replace(/^\.\//, '../deepseek-harness/'))
}

const toTypes = path => path
  .replace(/\/src\/(.+)\.ts$/, '/lib/types/$1.d.ts')
  .replace(/\/src\/(.+)$/, '/lib/types/$1')
  .replace(/\/src$/, '/lib/types')

const harnessTypes = Object.fromEntries(
  Object.entries(harnessSrc).map(([key, value]) => [key, value.map(toTypes)]),
)

const buildOwn = {
  '@wowyuarm/dsh-agent-team/host': ['./packages/agent-team/lib/types/index.d.ts'],
  '@wowyuarm/dsh-agent-team/invariant': ['./packages/agent-team/lib/types/invariant.d.ts'],
  '@wowyuarm/dsh-agent-team/types': ['./packages/agent-team/lib/types/types.d.ts'],
  '@wowyuarm/dsh-agent-team/typert': ['./packages/agent-team/lib/typert.host.d.ts'],
  '@wowyuarm/dsh-agent-team/remote': ['./packages/agent-team/lib/typert.remote-client.d.ts'],
  '@wowyuarm/dsh-agent-team/preset-roster': ['./packages/agent-team/lib/types/preset-roster.d.ts'],
  '@wowyuarm/dsh-agent-team/member-context': ['./packages/agent-team/lib/types/member-context.d.ts'],
  '@wowyuarm/dsh-agent-team/tools': ['./packages/tool-agent-team/lib/types/index.d.ts'],
  '@wowyuarm/dsh-agent-team/client': ['./packages/client-agent-team/lib/types/client/index.d.ts'],
}

const shared = {
  target: 'es2024', module: 'esnext', moduleResolution: 'bundler', skipLibCheck: true,
  esModuleInterop: true, allowImportingTsExtensions: true, rewriteRelativeImportExtensions: true,
  verbatimModuleSyntax: false, strict: true, noUncheckedIndexedAccess: true,
  exactOptionalPropertyTypes: true, noImplicitOverride: true, noFallthroughCasesInSwitch: true,
  types: ['node'], noEmit: true,
}

const header = text => `// GENERATED by scripts/sync-paths.mjs - edit that script, not this file.\n${text}`

writeFileSync(new URL('../tsconfig.json', import.meta.url), `${JSON.stringify({
  compilerOptions: { ...shared, paths: { ...own, ...harnessSrc } },
}, null, 2)}\n`.replace(/^/, header('// Runtime facade for the external bundle and sibling Harness source.\n')))

writeFileSync(new URL('../tsconfig.types.json', import.meta.url), `${JSON.stringify({
  compilerOptions: { ...shared, paths: { ...ownTypes, ...harnessTypes } },
}, null, 2)}\n`.replace(/^/, header('// Typecheck facade for the external bundle and sibling Harness declarations.\n')))

writeFileSync(new URL('../tsconfig.build-deps.json', import.meta.url), `${JSON.stringify({
  compilerOptions: { ...shared, paths: { ...buildOwn, ...harnessTypes } },
}, null, 2)}\n`.replace(/^/, header('// Build facade: own cross-surface imports resolve to emitted declarations.\n')))

console.log(`wrote tsconfig.json (${Object.keys(harnessSrc).length} Harness mappings), tsconfig.types.json, and tsconfig.build-deps.json`)
