// dsh adaptation of the codebase-ablation static import graph.
// Repo layout: pnpm-less npm monorepo, packages/*/src + packages/*/tests,
// explicit .ts/.tsx import extensions, self-package subpath imports via
// root tsconfig paths, generated typert artifacts in ignored lib/.
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import path from "node:path";

const EXTS = [".ts", ".tsx"];

export function listTsFiles(rootDir) {
  const out = [];
  const walk = (dir) => {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name === "node_modules" || entry.name === "lib" || entry.name === "dist") continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (EXTS.some((e) => entry.name.endsWith(e))) out.push(full);
    }
  };
  walk(rootDir);
  return out;
}

function resolveExact(p) {
  if (statSyncSafe(p)) return p;
  for (const e of EXTS) {
    if (statSyncSafe(p + e)) return p + e;
  }
  for (const e of EXTS) {
    const idx = path.join(p, `index${e}`);
    if (statSyncSafe(idx)) return idx;
  }
  return null;
}

function statSyncSafe(p) {
  try {
    return statSync(p).isFile();
  } catch {
    return false;
  }
}

// Subpath map mirrors the root tsconfig.json paths facade (generated by
// scripts/sync-paths.mjs; keep in sync when that script changes routes).
const SELF_PKG = "@wowyuarm/dsh-agent-team";
const SUBPATHS = new Map([
  [`${SELF_PKG}/host`, "packages/agent-team/src/index.ts"],
  [`${SELF_PKG}/invariant`, "packages/agent-team/src/invariant.ts"],
  [`${SELF_PKG}/types`, "packages/agent-team/src/types.ts"],
  [`${SELF_PKG}/preset-roster`, "packages/agent-team/src/preset-roster.ts"],
  [`${SELF_PKG}/member-context`, "packages/agent-team/src/member-context.ts"],
  [`${SELF_PKG}/member-skills`, "packages/agent-team/src/member-skills.ts"],
  [`${SELF_PKG}/tools`, "packages/tool-agent-team/src/index.ts"],
  [`${SELF_PKG}/client`, "packages/client-agent-team/src/client/index.ts"],
  [SELF_PKG, "packages/client-agent-team/src/index.ts"],
]);

function resolveImport(fromFile, spec, rootDir) {
  if (spec.startsWith(".")) return resolveExact(path.resolve(path.dirname(fromFile), spec));
  if (SUBPATHS.has(spec)) {
    const mapped = path.join(rootDir, SUBPATHS.get(spec));
    return statSyncSafe(mapped) ? mapped : null;
  }
  return null; // @deepseek-ai/* and other bare imports are external.
}

export function buildGraph(rootDir) {
  rootDir = path.resolve(rootDir);
  const files = new Map();
  const add = (abs) => {
    if (files.has(abs)) return;
    const text = readFileSync(abs, "utf8");
    const specs = [];
    for (const m of text.matchAll(/from\s*["']([^"']+)["']/g)) specs.push(m[1]);
    for (const m of text.matchAll(/import\s*["']([^"']+)["']/g)) specs.push(m[1]);
    for (const m of text.matchAll(/\bimport\s*\(\s*["']([^"']+)["']\s*\)/g)) specs.push(m[1]);
    const deps = [];
    for (const spec of specs) {
      const resolved = resolveImport(abs, spec, rootDir);
      if (resolved) deps.push(resolved);
    }
    files.set(abs, deps);
  };
  for (const pkg of readdirSync(path.join(rootDir, "packages")).sort()) {
    for (const root of ["src", "tests"]) {
      const dir = path.join(rootDir, "packages", pkg, root);
      if (existsSync(dir)) for (const f of listTsFiles(dir)) add(f);
    }
  }
  const scriptsDir = path.join(rootDir, "scripts");
  if (existsSync(scriptsDir)) for (const f of listTsFiles(scriptsDir)) add(f);
  return { files, rootDir };
}

export function reverseClosure(graph, targets) {
  const targetSet = new Set(targets);
  const importers = new Map();
  for (const [file, deps] of graph.files) {
    for (const dep of deps) {
      if (!importers.has(dep)) importers.set(dep, []);
      importers.get(dep).push(file);
    }
  }
  const removed = new Set(targetSet);
  const queue = [...targetSet];
  while (queue.length > 0) {
    const cur = queue.pop();
    for (const imp of importers.get(cur) ?? []) {
      if (!removed.has(imp)) {
        removed.add(imp);
        queue.push(imp);
      }
    }
  }
  return [...removed].sort();
}
